# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartinfo',
            name='ctoun',
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
